[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  functions = "netlify/functions/"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
